cmake_minimum_required(VERSION 3.23)

if(NOT DEFINED PRISTINE_ROOT_DIR)
  get_filename_component(PRISTINE_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
else()
  get_filename_component(PRISTINE_ROOT_DIR "${PRISTINE_ROOT_DIR}" ABSOLUTE)
endif()

if(NOT DEFINED PRISTINE_ATTRIBUTIONS_OUTPUT)
  set(PRISTINE_ATTRIBUTIONS_OUTPUT "${PRISTINE_ROOT_DIR}/ATTRIBUTIONS.md")
endif()

if(NOT DEFINED PRISTINE_NOTICE_OUTPUT)
  set(PRISTINE_NOTICE_OUTPUT "${PRISTINE_ROOT_DIR}/NOTICE")
endif()

if(NOT DEFINED PRISTINE_VALIDATE_ONLY)
  set(PRISTINE_VALIDATE_ONLY OFF)
endif()

include("${PRISTINE_ROOT_DIR}/cmake/attributions.cmake")

macro(pristine_normalize_newlines input output)
  string(REPLACE "\r\n" "\n" ${output} "${input}")
  string(REPLACE "\r" "\n" ${output} "${${output}}")
endmacro()

function(pristine_require_family family_id)
  list(FIND PRISTINE_NOTICE_FAMILY_IDS "${family_id}" family_index)
  if(family_index EQUAL -1)
    message(FATAL_ERROR "Attribution references unknown notice family '${family_id}'")
  endif()
endfunction()

function(pristine_emit_file path content description)
  if(PRISTINE_VALIDATE_ONLY)
    if(NOT EXISTS "${path}")
      message(FATAL_ERROR "${description} is missing at ${path}")
    endif()

    file(READ "${path}" existing_content)
    pristine_normalize_newlines("${existing_content}" existing_content)
    if(NOT existing_content STREQUAL content)
      message(
        FATAL_ERROR
          "${description} is out of date at ${path}. Re-run `cmake -DPRISTINE_ROOT_DIR=${PRISTINE_ROOT_DIR} -P scripts/generate-notice.cmake`.")
    endif()
  else()
    file(WRITE "${path}" "${content}")
    message(STATUS "Wrote ${description} to ${path}")
  endif()
endfunction()

set(attributions_content "# Third-Party Attributions\n\n")
string(APPEND attributions_content "This file is generated from `cmake/attributions.cmake`.\n")
string(APPEND attributions_content "It inventories the third-party components redistributed in the `pristine-lsp` install tree.\n\n")
string(APPEND attributions_content "| Component | Version | Relationship | License | Owner | Upstream |\n")
string(APPEND attributions_content "| --- | --- | --- | --- | --- | --- |\n")

set(redistributed_ids "")
foreach(attribution_id IN LISTS PRISTINE_ATTRIBUTION_IDS)
  set(name "${PRISTINE_ATTRIBUTION_${attribution_id}_NAME}")
  set(version "${PRISTINE_ATTRIBUTION_${attribution_id}_VERSION}")
  set(relationship "${PRISTINE_ATTRIBUTION_${attribution_id}_RELATIONSHIP}")
  set(license_label "${PRISTINE_ATTRIBUTION_${attribution_id}_LICENSE_LABEL}")
  set(owner "${PRISTINE_ATTRIBUTION_${attribution_id}_OWNER}")
  set(url "${PRISTINE_ATTRIBUTION_${attribution_id}_URL}")
  set(scope "${PRISTINE_ATTRIBUTION_${attribution_id}_SCOPE}")

  string(APPEND attributions_content "| ${name} | ${version} | ${relationship} | ${license_label} | ${owner} | ${url} |\n")

  if(scope STREQUAL "redistributed")
    list(APPEND redistributed_ids "${attribution_id}")
  endif()

  foreach(family_id IN LISTS PRISTINE_ATTRIBUTION_${attribution_id}_FAMILY_IDS)
    pristine_require_family("${family_id}")
  endforeach()
endforeach()

if(NOT redistributed_ids)
  message(FATAL_ERROR "No redistributed attribution entries were declared")
endif()

set(used_family_ids "")
foreach(attribution_id IN LISTS redistributed_ids)
  foreach(family_id IN LISTS PRISTINE_ATTRIBUTION_${attribution_id}_FAMILY_IDS)
    list(APPEND used_family_ids "${family_id}")
  endforeach()
endforeach()
list(REMOVE_DUPLICATES used_family_ids)

set(notice_content "Third-Party Notices for pristine-engine\n\n")
string(APPEND notice_content "This file is generated from cmake/attributions.cmake.\n")
string(APPEND notice_content "It covers the third-party components redistributed in the pristine-lsp install tree.\n\n")
string(APPEND notice_content "Bundled notice files:\n")
string(APPEND notice_content "- LICENSE\n")
string(APPEND notice_content "- ATTRIBUTIONS.md\n")
string(APPEND notice_content "- NOTICE\n\n")
string(APPEND notice_content "Redistributed components:\n")

foreach(attribution_id IN LISTS redistributed_ids)
  set(name "${PRISTINE_ATTRIBUTION_${attribution_id}_NAME}")
  set(version "${PRISTINE_ATTRIBUTION_${attribution_id}_VERSION}")
  set(license_label "${PRISTINE_ATTRIBUTION_${attribution_id}_LICENSE_LABEL}")
  set(owner "${PRISTINE_ATTRIBUTION_${attribution_id}_OWNER}")
  set(url "${PRISTINE_ATTRIBUTION_${attribution_id}_URL}")
  string(APPEND notice_content "- ${name} ${version} (${license_label}) - ${owner}\n")
  string(APPEND notice_content "  ${url}\n")
endforeach()

foreach(family_id IN LISTS used_family_ids)
  set(family_title "${PRISTINE_NOTICE_FAMILY_${family_id}_TITLE}")
  set(family_source_path "${PRISTINE_NOTICE_FAMILY_${family_id}_SOURCE_PATH}")
  set(family_note "${PRISTINE_NOTICE_FAMILY_${family_id}_NOTE}")

  if(NOT EXISTS "${family_source_path}")
    message(FATAL_ERROR "Notice family '${family_id}' is missing source text at ${family_source_path}")
  endif()

  file(READ "${family_source_path}" family_text)
  pristine_normalize_newlines("${family_text}" family_text)
  string(STRIP "${family_text}" family_text)

  string(APPEND notice_content "\n================================================================================\n")
  string(APPEND notice_content "${family_title}\n")
  string(APPEND notice_content "================================================================================\n")
  if(family_note)
    string(APPEND notice_content "${family_note}\n")
  endif()
  string(APPEND notice_content "\nCovered components:\n")

  foreach(attribution_id IN LISTS redistributed_ids)
    set(component_families "${PRISTINE_ATTRIBUTION_${attribution_id}_FAMILY_IDS}")
    list(FIND component_families "${family_id}" family_member_index)
    if(family_member_index GREATER -1)
      set(name "${PRISTINE_ATTRIBUTION_${attribution_id}_NAME}")
      set(version "${PRISTINE_ATTRIBUTION_${attribution_id}_VERSION}")
      set(owner "${PRISTINE_ATTRIBUTION_${attribution_id}_OWNER}")
      string(APPEND notice_content "- ${name} ${version} - ${owner}\n")
    endif()
  endforeach()

  string(APPEND notice_content "\n${family_text}\n")
endforeach()

pristine_emit_file("${PRISTINE_ATTRIBUTIONS_OUTPUT}" "${attributions_content}" "ATTRIBUTIONS.md")
pristine_emit_file("${PRISTINE_NOTICE_OUTPUT}" "${notice_content}" "NOTICE")